# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import vprikol_pb2 as vprikol_dot_v1_dot_vprikol__pb2


class VprikolAPIStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStatus = channel.unary_unary(
                '/vprikol.v1.VprikolAPI/GetStatus',
                request_serializer=vprikol_dot_v1_dot_vprikol__pb2.GetStatusRequest.SerializeToString,
                response_deserializer=vprikol_dot_v1_dot_vprikol__pb2.GetStatusResponse.FromString,
                )
        self.GetRating = channel.unary_unary(
                '/vprikol.v1.VprikolAPI/GetRating',
                request_serializer=vprikol_dot_v1_dot_vprikol__pb2.GetRatingRequest.SerializeToString,
                response_deserializer=vprikol_dot_v1_dot_vprikol__pb2.RatingResponse.FromString,
                )
        self.GetEstate = channel.unary_unary(
                '/vprikol.v1.VprikolAPI/GetEstate',
                request_serializer=vprikol_dot_v1_dot_vprikol__pb2.GetEstateRequest.SerializeToString,
                response_deserializer=vprikol_dot_v1_dot_vprikol__pb2.EstateResponse.FromString,
                )
        self.GetLeaders = channel.unary_unary(
                '/vprikol.v1.VprikolAPI/GetLeaders',
                request_serializer=vprikol_dot_v1_dot_vprikol__pb2.ServerRequest.SerializeToString,
                response_deserializer=vprikol_dot_v1_dot_vprikol__pb2.LeadersResponse.FromString,
                )
        self.GetDeputies = channel.unary_unary(
                '/vprikol.v1.VprikolAPI/GetDeputies',
                request_serializer=vprikol_dot_v1_dot_vprikol__pb2.ServerRequest.SerializeToString,
                response_deserializer=vprikol_dot_v1_dot_vprikol__pb2.LeadersResponse.FromString,
                )
        self.GetInterviews = channel.unary_unary(
                '/vprikol.v1.VprikolAPI/GetInterviews',
                request_serializer=vprikol_dot_v1_dot_vprikol__pb2.ServerRequest.SerializeToString,
                response_deserializer=vprikol_dot_v1_dot_vprikol__pb2.InterviewsResponse.FromString,
                )
        self.GetPlayers = channel.unary_unary(
                '/vprikol.v1.VprikolAPI/GetPlayers',
                request_serializer=vprikol_dot_v1_dot_vprikol__pb2.ServerRequest.SerializeToString,
                response_deserializer=vprikol_dot_v1_dot_vprikol__pb2.PlayersResponse.FromString,
                )
        self.GetMap = channel.unary_unary(
                '/vprikol.v1.VprikolAPI/GetMap',
                request_serializer=vprikol_dot_v1_dot_vprikol__pb2.GetMapRequest.SerializeToString,
                response_deserializer=vprikol_dot_v1_dot_vprikol__pb2.MapResponse.FromString,
                )
        self.GetMapZones = channel.unary_unary(
                '/vprikol.v1.VprikolAPI/GetMapZones',
                request_serializer=vprikol_dot_v1_dot_vprikol__pb2.ServerRequest.SerializeToString,
                response_deserializer=vprikol_dot_v1_dot_vprikol__pb2.MapZonesResponse.FromString,
                )
        self.GetFractionMembers = channel.unary_unary(
                '/vprikol.v1.VprikolAPI/GetFractionMembers',
                request_serializer=vprikol_dot_v1_dot_vprikol__pb2.GetFractionMembersRequest.SerializeToString,
                response_deserializer=vprikol_dot_v1_dot_vprikol__pb2.MembersResponse.FromString,
                )
        self.FindPlayer = channel.unary_unary(
                '/vprikol.v1.VprikolAPI/FindPlayer',
                request_serializer=vprikol_dot_v1_dot_vprikol__pb2.FindPlayerRequest.SerializeToString,
                response_deserializer=vprikol_dot_v1_dot_vprikol__pb2.FindPlayerResponse.FromString,
                )
        self.GetPlayerOnline = channel.unary_unary(
                '/vprikol.v1.VprikolAPI/GetPlayerOnline',
                request_serializer=vprikol_dot_v1_dot_vprikol__pb2.GetPlayerOnlineRequest.SerializeToString,
                response_deserializer=vprikol_dot_v1_dot_vprikol__pb2.OnlineResponse.FromString,
                )
        self.GetPlayerHistory = channel.unary_unary(
                '/vprikol.v1.VprikolAPI/GetPlayerHistory',
                request_serializer=vprikol_dot_v1_dot_vprikol__pb2.GetPlayerHistoryRequest.SerializeToString,
                response_deserializer=vprikol_dot_v1_dot_vprikol__pb2.PlayerHistoryResponse.FromString,
                )
        self.GetPunishes = channel.unary_unary(
                '/vprikol.v1.VprikolAPI/GetPunishes',
                request_serializer=vprikol_dot_v1_dot_vprikol__pb2.GetPunishesRequest.SerializeToString,
                response_deserializer=vprikol_dot_v1_dot_vprikol__pb2.PunishHistoryResponse.FromString,
                )
        self.GetTokenInfo = channel.unary_unary(
                '/vprikol.v1.VprikolAPI/GetTokenInfo',
                request_serializer=vprikol_dot_v1_dot_vprikol__pb2.GetTokenInfoRequest.SerializeToString,
                response_deserializer=vprikol_dot_v1_dot_vprikol__pb2.TokenResponse.FromString,
                )
        self.GetTokenRequests = channel.unary_unary(
                '/vprikol.v1.VprikolAPI/GetTokenRequests',
                request_serializer=vprikol_dot_v1_dot_vprikol__pb2.GetTokenRequestsRequest.SerializeToString,
                response_deserializer=vprikol_dot_v1_dot_vprikol__pb2.RequestLogResponse.FromString,
                )
        self.GetTokenRequestsStats = channel.unary_unary(
                '/vprikol.v1.VprikolAPI/GetTokenRequestsStats',
                request_serializer=vprikol_dot_v1_dot_vprikol__pb2.GetTokenRequestsStatsRequest.SerializeToString,
                response_deserializer=vprikol_dot_v1_dot_vprikol__pb2.RequestStatsResponse.FromString,
                )


class VprikolAPIServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRating(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEstate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLeaders(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDeputies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInterviews(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPlayers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMap(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMapZones(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFractionMembers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindPlayer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPlayerOnline(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPlayerHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPunishes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTokenInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTokenRequests(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTokenRequestsStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VprikolAPIServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=vprikol_dot_v1_dot_vprikol__pb2.GetStatusRequest.FromString,
                    response_serializer=vprikol_dot_v1_dot_vprikol__pb2.GetStatusResponse.SerializeToString,
            ),
            'GetRating': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRating,
                    request_deserializer=vprikol_dot_v1_dot_vprikol__pb2.GetRatingRequest.FromString,
                    response_serializer=vprikol_dot_v1_dot_vprikol__pb2.RatingResponse.SerializeToString,
            ),
            'GetEstate': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEstate,
                    request_deserializer=vprikol_dot_v1_dot_vprikol__pb2.GetEstateRequest.FromString,
                    response_serializer=vprikol_dot_v1_dot_vprikol__pb2.EstateResponse.SerializeToString,
            ),
            'GetLeaders': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLeaders,
                    request_deserializer=vprikol_dot_v1_dot_vprikol__pb2.ServerRequest.FromString,
                    response_serializer=vprikol_dot_v1_dot_vprikol__pb2.LeadersResponse.SerializeToString,
            ),
            'GetDeputies': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDeputies,
                    request_deserializer=vprikol_dot_v1_dot_vprikol__pb2.ServerRequest.FromString,
                    response_serializer=vprikol_dot_v1_dot_vprikol__pb2.LeadersResponse.SerializeToString,
            ),
            'GetInterviews': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInterviews,
                    request_deserializer=vprikol_dot_v1_dot_vprikol__pb2.ServerRequest.FromString,
                    response_serializer=vprikol_dot_v1_dot_vprikol__pb2.InterviewsResponse.SerializeToString,
            ),
            'GetPlayers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlayers,
                    request_deserializer=vprikol_dot_v1_dot_vprikol__pb2.ServerRequest.FromString,
                    response_serializer=vprikol_dot_v1_dot_vprikol__pb2.PlayersResponse.SerializeToString,
            ),
            'GetMap': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMap,
                    request_deserializer=vprikol_dot_v1_dot_vprikol__pb2.GetMapRequest.FromString,
                    response_serializer=vprikol_dot_v1_dot_vprikol__pb2.MapResponse.SerializeToString,
            ),
            'GetMapZones': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMapZones,
                    request_deserializer=vprikol_dot_v1_dot_vprikol__pb2.ServerRequest.FromString,
                    response_serializer=vprikol_dot_v1_dot_vprikol__pb2.MapZonesResponse.SerializeToString,
            ),
            'GetFractionMembers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFractionMembers,
                    request_deserializer=vprikol_dot_v1_dot_vprikol__pb2.GetFractionMembersRequest.FromString,
                    response_serializer=vprikol_dot_v1_dot_vprikol__pb2.MembersResponse.SerializeToString,
            ),
            'FindPlayer': grpc.unary_unary_rpc_method_handler(
                    servicer.FindPlayer,
                    request_deserializer=vprikol_dot_v1_dot_vprikol__pb2.FindPlayerRequest.FromString,
                    response_serializer=vprikol_dot_v1_dot_vprikol__pb2.FindPlayerResponse.SerializeToString,
            ),
            'GetPlayerOnline': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlayerOnline,
                    request_deserializer=vprikol_dot_v1_dot_vprikol__pb2.GetPlayerOnlineRequest.FromString,
                    response_serializer=vprikol_dot_v1_dot_vprikol__pb2.OnlineResponse.SerializeToString,
            ),
            'GetPlayerHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlayerHistory,
                    request_deserializer=vprikol_dot_v1_dot_vprikol__pb2.GetPlayerHistoryRequest.FromString,
                    response_serializer=vprikol_dot_v1_dot_vprikol__pb2.PlayerHistoryResponse.SerializeToString,
            ),
            'GetPunishes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPunishes,
                    request_deserializer=vprikol_dot_v1_dot_vprikol__pb2.GetPunishesRequest.FromString,
                    response_serializer=vprikol_dot_v1_dot_vprikol__pb2.PunishHistoryResponse.SerializeToString,
            ),
            'GetTokenInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTokenInfo,
                    request_deserializer=vprikol_dot_v1_dot_vprikol__pb2.GetTokenInfoRequest.FromString,
                    response_serializer=vprikol_dot_v1_dot_vprikol__pb2.TokenResponse.SerializeToString,
            ),
            'GetTokenRequests': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTokenRequests,
                    request_deserializer=vprikol_dot_v1_dot_vprikol__pb2.GetTokenRequestsRequest.FromString,
                    response_serializer=vprikol_dot_v1_dot_vprikol__pb2.RequestLogResponse.SerializeToString,
            ),
            'GetTokenRequestsStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTokenRequestsStats,
                    request_deserializer=vprikol_dot_v1_dot_vprikol__pb2.GetTokenRequestsStatsRequest.FromString,
                    response_serializer=vprikol_dot_v1_dot_vprikol__pb2.RequestStatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vprikol.v1.VprikolAPI', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class VprikolAPI(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vprikol.v1.VprikolAPI/GetStatus',
            vprikol_dot_v1_dot_vprikol__pb2.GetStatusRequest.SerializeToString,
            vprikol_dot_v1_dot_vprikol__pb2.GetStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRating(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vprikol.v1.VprikolAPI/GetRating',
            vprikol_dot_v1_dot_vprikol__pb2.GetRatingRequest.SerializeToString,
            vprikol_dot_v1_dot_vprikol__pb2.RatingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetEstate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vprikol.v1.VprikolAPI/GetEstate',
            vprikol_dot_v1_dot_vprikol__pb2.GetEstateRequest.SerializeToString,
            vprikol_dot_v1_dot_vprikol__pb2.EstateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetLeaders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vprikol.v1.VprikolAPI/GetLeaders',
            vprikol_dot_v1_dot_vprikol__pb2.ServerRequest.SerializeToString,
            vprikol_dot_v1_dot_vprikol__pb2.LeadersResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDeputies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vprikol.v1.VprikolAPI/GetDeputies',
            vprikol_dot_v1_dot_vprikol__pb2.ServerRequest.SerializeToString,
            vprikol_dot_v1_dot_vprikol__pb2.LeadersResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetInterviews(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vprikol.v1.VprikolAPI/GetInterviews',
            vprikol_dot_v1_dot_vprikol__pb2.ServerRequest.SerializeToString,
            vprikol_dot_v1_dot_vprikol__pb2.InterviewsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPlayers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vprikol.v1.VprikolAPI/GetPlayers',
            vprikol_dot_v1_dot_vprikol__pb2.ServerRequest.SerializeToString,
            vprikol_dot_v1_dot_vprikol__pb2.PlayersResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vprikol.v1.VprikolAPI/GetMap',
            vprikol_dot_v1_dot_vprikol__pb2.GetMapRequest.SerializeToString,
            vprikol_dot_v1_dot_vprikol__pb2.MapResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMapZones(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vprikol.v1.VprikolAPI/GetMapZones',
            vprikol_dot_v1_dot_vprikol__pb2.ServerRequest.SerializeToString,
            vprikol_dot_v1_dot_vprikol__pb2.MapZonesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetFractionMembers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vprikol.v1.VprikolAPI/GetFractionMembers',
            vprikol_dot_v1_dot_vprikol__pb2.GetFractionMembersRequest.SerializeToString,
            vprikol_dot_v1_dot_vprikol__pb2.MembersResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FindPlayer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vprikol.v1.VprikolAPI/FindPlayer',
            vprikol_dot_v1_dot_vprikol__pb2.FindPlayerRequest.SerializeToString,
            vprikol_dot_v1_dot_vprikol__pb2.FindPlayerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPlayerOnline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vprikol.v1.VprikolAPI/GetPlayerOnline',
            vprikol_dot_v1_dot_vprikol__pb2.GetPlayerOnlineRequest.SerializeToString,
            vprikol_dot_v1_dot_vprikol__pb2.OnlineResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPlayerHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vprikol.v1.VprikolAPI/GetPlayerHistory',
            vprikol_dot_v1_dot_vprikol__pb2.GetPlayerHistoryRequest.SerializeToString,
            vprikol_dot_v1_dot_vprikol__pb2.PlayerHistoryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPunishes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vprikol.v1.VprikolAPI/GetPunishes',
            vprikol_dot_v1_dot_vprikol__pb2.GetPunishesRequest.SerializeToString,
            vprikol_dot_v1_dot_vprikol__pb2.PunishHistoryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTokenInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vprikol.v1.VprikolAPI/GetTokenInfo',
            vprikol_dot_v1_dot_vprikol__pb2.GetTokenInfoRequest.SerializeToString,
            vprikol_dot_v1_dot_vprikol__pb2.TokenResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTokenRequests(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vprikol.v1.VprikolAPI/GetTokenRequests',
            vprikol_dot_v1_dot_vprikol__pb2.GetTokenRequestsRequest.SerializeToString,
            vprikol_dot_v1_dot_vprikol__pb2.RequestLogResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTokenRequestsStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vprikol.v1.VprikolAPI/GetTokenRequestsStats',
            vprikol_dot_v1_dot_vprikol__pb2.GetTokenRequestsStatsRequest.SerializeToString,
            vprikol_dot_v1_dot_vprikol__pb2.RequestStatsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
